<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML240ENSkillsNetwork34171862-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>


# ***Machine Learning Foundation***

## ***Theme: Regularization***


$ \ $

------

## ***Learning objectives***

By the end of this lesson, you will be able to:

*   Implement data standardization.

*   Implement variants of regularized regression.

*   Combine data standardization with the train-test split procedure.

*   Implement regularization to prevent overfitting in regression problems.


$ \ $

----

## ***Import some packages***

We import some packages ans supress the warnings.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
# Surpress warnings:
def warn(*args, **kwargs):
    pass

In [ ]:
import warnings
warnings.warn = warn

np.set_printoptions(precision=3, suppress=True)

$ \ $

----

## ***Useful plotting functions***

In the following cells we load the data and define some useful plotting functions.


In [ ]:
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()

In [ ]:
np.random.seed(72018)

def to_2d(array):
    return array.reshape(array.shape[0], -1)

In [ ]:
def california_dataframe(description = False):

    #(1) buscar vivivienda en california
    california = fetch_california_housing()
    
    #(2) cargamos los rasgos en las correspondientes variables
    data = california["data"]
    target = california["target"]
    names = california["feature_names"]
    
    #(3) usamos la funcion to_2d
    target = to_2d(target)
    
    #(4) concatenamos algunos datos
    data_all = np.concatenate([data, target], axis=1)
    names_all = np.concatenate([names, np.array(['MEDV'])], axis=0)
    
    #(5) 
    if description:
        
        return pd.DataFrame(data = data_all, columns = names_all), california.DESCR
    
    else: 
        
        return pd.DataFrame(data = data_all, columns = names_all)  

$ \ $

----

## ***Loading in california Data***

We get the data.


In [ ]:
california = california_dataframe(description = True)
california_data = california[0]
california_description = california[1]

$ \ $

-----

## ***Data standardization***

Standardizing data refers to transforming each variable so that it more closely follows a standard normal distribution, with mean $0$ and standard deviation $1$. The [`StandardScaler`](http://scikit-learn.org/dev/modules/generated/sklearn.preprocessing.StandardScaler.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML240ENSkillsNetwork34171862-2022-01-01#sklearn.preprocessing.StandardScaler) object in SciKit Learn can do this.

$ \ $


$(1)$ Generate $X$ and $y$.



In [ ]:
X = california_data.drop("MEDV", axis=1)
X

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [ ]:
y = california_data["MEDV"]
y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...  
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: MEDV, Length: 20640, dtype: float64

$ \ $

$(2)$ Import, fit, and transform using `StandardScaler`.


In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
# el escalamiento estandar es el usual (x-\mu)/(\sigma)
s = StandardScaler()
X_ss = s.fit_transform(X)

$ \ $

----

## ***Exercise***

Confirm standard scaling.

$ \ $

$\underline{\text{Hint:}}$ Remember the following things.



In [ ]:
a = np.array([[1, 2, 3], 
              [4, 5, 6]]) 
print(a) 

[[1 2 3]
 [4 5 6]]


In [ ]:
#  obtenemos el promedio de cada columna
a.mean(axis = 0) 

array([2.5, 3.5, 4.5])

In [ ]:
# obtemos el promedio de cada renglon
a.mean(axis = 1) 

array([2., 5.])

In [ ]:
# tomamos un array de la data X
X2 = np.array(X)
X2 

array([[   8.325,   41.   ,    6.984, ...,    2.556,   37.88 , -122.23 ],
       [   8.301,   21.   ,    6.238, ...,    2.11 ,   37.86 , -122.22 ],
       [   7.257,   52.   ,    8.288, ...,    2.802,   37.85 , -122.24 ],
       ...,
       [   1.7  ,   17.   ,    5.206, ...,    2.326,   39.43 , -121.22 ],
       [   1.867,   18.   ,    5.33 , ...,    2.123,   39.43 , -121.32 ],
       [   2.389,   16.   ,    5.255, ...,    2.617,   39.37 , -121.24 ]])

$ \ $

#### $\underline{\text{Answer:}}$

In [ ]:
# restamos nuestra el promedio de cada columna a nuestro conjunto de datos
num = X2-X2.mean(axis = 0)

# obtenemos la desviacion estandar de cada columna del array X2
den = X2.std(axis = 0)

# tomamos el cociente de los datos anteriores
man_transform = num / den

In [ ]:
# Devuelve True si dos matrices son iguales en cuanto a elementos dentro de una tolerancia.
np.allclose(man_transform, X_ss)

True

$ \ $

----

## ***Coefficients with and without scaling***

$ \ $

$(1)$ We import the linear regression package.


In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

$ \ $

$(2)$ We describe the data that we are going to use.

In [ ]:
X = california_data.drop("MEDV", axis = 1)
y = california_data["MEDV"]

$ \ $

$(3)$ We train our linear regression model.

In [ ]:
lr.fit(X, y)

LinearRegression()

$ \ $

$(4)$ We show the coefficients of the trained linear regression model.

In [ ]:
lr.coef_

array([ 0.437,  0.009, -0.107,  0.645, -0.   , -0.004, -0.421, -0.435])

$ \ $

$(5)$ The coefficients are on widely different scales. Is this "bad"?


In [ ]:
from sklearn.preprocessing import StandardScaler
s = StandardScaler()

In [ ]:
# entrenamos nuestro modelo de escala con la data X
X_ss = s.fit_transform(X)

In [ ]:
# creamos un modelo de regresion lineal
lr2 = LinearRegression()

# entrenamos nuestro modelo con la data X_ss and Y
lr2.fit(X_ss, y)

LinearRegression()

In [ ]:
#mostramos los coeficientes obtenidos del modelo de regresion lineal despues de haber sido entrenado
print(lr2.coef_) 

[ 0.83   0.119 -0.266  0.306 -0.005 -0.039 -0.9   -0.871]


$ \ $

----

## ***Exercise***

Based on these results,

* What is the most "impactful"  feature (this is intended to be slightly ambiguous)? 

* "In what direction" does it affect $y$?




In [ ]:
X.columns

Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude'],
      dtype='object')

In [ ]:
lr2.coef_

array([ 0.83 ,  0.119, -0.266,  0.306, -0.005, -0.039, -0.9  , -0.871])

In [ ]:
pd.DataFrame(zip(X.columns, lr2.coef_)).sort_values(by=1)

0         1
6    Latitude -0.899886
7   Longitude -0.870541
2    AveRooms -0.265527
5    AveOccup -0.039326
4  Population -0.004503
1    HouseAge  0.118752
3   AveBedrms  0.305696
0      MedInc  0.829619

$ \ $

----

## ***Lasso with and without scaling***



Let's review together:

*  What is different about Lasso vs. regular Linear Regression?


*  Is standardization more or less important with Lasso vs. Linear Regression? Why?

$ \ $

$(1)$ To begin with, we import the necessary packages.



In [ ]:
from sklearn.linear_model import Lasso
from sklearn.preprocessing import PolynomialFeatures

$ \ $

$(2)$ We create the polynomial features.


In [ ]:
pf = PolynomialFeatures(degree = 2, include_bias = False) 

$ \ $

$(3)$ We train our polynomial model.

In [ ]:
X_pf = pf.fit_transform(X)

$ \ $

$(4)$ We get a predictive data using the standardscaler model with the data $X_{pf}$.

In [ ]:
# s = StandardScaler()
X_pf_ss = s.fit_transform(X_pf)

$ \ $ 



$(5)$ We create a lasso model. The documentation of lasso is given in the following link.

[link - Lasso](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Lasso.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML240ENSkillsNetwork34171862-2022-01-01)



In [ ]:
las = Lasso()

$ \ $

$(6)$ We train our lasso model with the data $X$_pf_ss and $y$.

In [ ]:
las.fit(X_pf_ss, y)

Lasso()

$ \ $

$(7)$ We show the coeficients of our trained model.

In [ ]:
las.coef_ 

array([ 0.,  0.,  0., -0., -0., -0., -0., -0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0., -0.,  0.,  0.,  0.,  0., -0.,  0., -0.,  0.,  0.,  0.,
        0.,  0., -0., -0., -0., -0., -0.,  0., -0., -0., -0.,  0., -0.,
       -0.,  0., -0.,  0.,  0.])

$ \ $

---

## ***Exercise***

$(1)$ Compare

*   Sum of magnitudes of the coefficients
*   Number of coefficients that are zero

for Lasso with alpha $0.1$ vs. $1$.

In [ ]:
# pf = PolynomialFeatures(degree = 2, include_bias = False) 
# X_pf = pf.fit_transform(X)
# s = StandardScaler()
# X_pf_ss = s.fit_transform(X_pf)
# y = california_data["MEDV"]

In [ ]:
# creamos un modelo de tipo lasso con alpha = 0.1
las01 = Lasso(alpha = 0.1)

# entrenamos nuestro modelo lasso con la data X_pf_ss, y
las01.fit(X_pf_ss, y)

Lasso(alpha=0.1)

In [ ]:
# creamos un modelo de tipo lasso con alpha = 1
las1 = Lasso(alpha = 1)

# entrenamos nuestro modelo lasso con la data X_pf_ss, y
las1.fit(X_pf_ss, y)

Lasso(alpha=1)

In [ ]:
print('Sum of coefficients:', abs(las01.coef_).sum() )
print('Number of coefficients not equal to zero:', (las01.coef_!=0).sum())

Sum of coefficients: 0.7973742355027422
Number of coefficients not equal to zero: 3


In [ ]:
print('Sum of coefficients:', abs(las1.coef_).sum() )
print('Number of coefficients not equal to zero:', (las1.coef_!=0).sum())

Sum of coefficients: 0.0
Number of coefficients not equal to zero: 0


$ \ $

$(2)$ Answer the following questions in one sentence each:

$ \ $

$(a)$  Which do you expect to have greater magnitude?

With more regularization (higher alpha) we will expect the penalty for higher weights to be greater and thus the coefficients to be pushed down.

$ \ $

$(b)$   Which do you expect to have more zeros?

A higher alpha means lower magnitude with more coefficients pushed down to $0$.

$ \ $

-----

## ***Exercise $R^{2}$***

$(1)$ We begin with importing $R^2$.


In [ ]:
from sklearn.metrics import r2_score

$ \ $

$(2)$ Calculate the $R^2$ of each model without (train/test) split.

In [ ]:
# pf = PolynomialFeatures(degree=2, include_bias=False) 
# X_pf = pf.fit_transform(X)
# s = StandardScaler()
# X_pf_ss = s.fit_transform(X_pf)

In [ ]:
# predecimos un conjunto de datos con nuestro modelo las y la data X_pf_ss
y_pred = las.predict(X_pf_ss)

# calculamos el R^2 de cada modelo entrenado 
r2_score(y, y_pred)

0.0

$ \ $

$(3)$ We import the train_test_split.

In [ ]:
from sklearn.model_selection import train_test_split 

$ \ $

$(4)$ We use the function train_test_split on the data $X_{pf}$ and $y$.

In [ ]:
# X_pf =  pf.fit_transform(X)
# y = california_data["MEDV"]
X_train, X_test, y_train, y_test = train_test_split(X_pf, y, test_size = 0.3, random_state = 72018)

$ \ $

$(5)$ We train our $s$ model and $las$ model.

In [ ]:
# s = StandardScaler()
# entrenamos nuestro modelo s con la data X_train
X_train_s = s.fit_transform(X_train)

# las = Lasso()
# entrenamos nuestro modelo las con la data X_train_s, y_train
las.fit(X_train_s, y_train)

Lasso()

$ \ $

$(6)$ We predict some data from the $s$ model and $las$ model.

In [ ]:
# obtenemos un conjunto de datos de prueba con el modelo s y la data X_test
X_test_s = s.transform(X_test)

# predecimos un conjunto de datos con el modelo las y la data X_test_s
y_pred = las.predict(X_test_s)

$ \ $

$(7)$ We calculate  $R^2$ of each trained model.

In [ ]:
r2_score(y_pred, y_test)

-6.801014422034886e+30

$ \ $

$(8)$ We repeat the steps $5, 6$ and $7$ with $las01$.

In [ ]:
# s = StandardScaler()
# entrenamos nuestro modelo s con la data X_train
X_train_s = s.fit_transform(X_train)

# las01 = Lasso(alpha = 0.1)
# entrenamos nuestro modelo las01 con la data X_train_s, y_train
las01.fit(X_train_s, y_train)

# obtenemos un conjunto de datos de prueba con el modelo s y la data X_test
X_test_s = s.transform(X_test)

# predecimos un conjunto de datos con el modelo las01 y la data X_test_s
y_pred = las01.predict(X_test_s)

#  calculamos el R^2 de cada modelo entrenado 
r2_score(y_pred, y_test)

-0.22121083796244

$ \ $

-----

## ***Exercise***

$(1)$ Do the same thing with Lasso of:

* $\alpha$ of $0.001$.

* Increase `max_iter` to $100000$ to ensure convergence.

* Calculate the $R^2$ of the model.

* Feel free to copy-paste code from above, but write a one sentence comment above each line of code explaining why you're doing what you're doing.

In [ ]:
# Reducir el valor de alpha e incrementamos el numero maximo de iteraciones para garantizar la convergencia
las001 = Lasso(alpha = 0.001, max_iter = 100000)

In [ ]:
# Transforming training set to get standardized units
X_train_s = s.fit_transform(X_train)

# Fitting model to training set
las001.fit(X_train_s, y_train)

Lasso(alpha=0.001, max_iter=100000)

In [ ]:
# Transformamos el conjunto de prueba usando los parámetros definidos del conjunto de entrenamiento X_test
X_test_s = s.transform(X_test)

# encontramos la prediccion del modelo las001 usando la data X_test_s
y_pred = las001.predict(X_test_s)

In [ ]:
# calculamos el r2 score para alpha=0.001 teniendo en cuenta la data y_pred (predecida), y_test(prueba)
print("r2 score for alpha = 0.001:", r2_score(y_pred, y_test))

r2 score for alpha = 0.001: 0.4646258681355345


$ \ $

$(2)$ Do the same procedure as before, but with Linear Regression.

* Calculate the $R^2$ of this model.

In [ ]:
# creamos un modelo  de regresion lineal
lr = LinearRegression()

# entrenamos nuestro modelo de regresion lineal con la data X_train_s, y_train
lr.fit(X_train_s, y_train)

# predecimos un conjunto de datos usando nuestro modelo de regresion lineal usando la data X_test_s
y_pred_lr = lr.predict(X_test_s)

# Calculamos el R^2 score
print("R^2 score for Linear Regression:", r2_score(y_pred_lr, y_test))

R^2 score for Linear Regression: 0.4871823555977194


$ \ $

$(3)$ Compare the sums of the absolute values of the coefficients for both models, as well as the number of coefficients that are zero. 

In [ ]:
print('Magnitude of Lasso coefficients:', abs(las001.coef_).sum())
print('Number of coeffients not equal to 0 for Lasso:', (las001.coef_!=0).sum())

Magnitude of Lasso coefficients: 13.797961138605485
Number of coeffients not equal to 0 for Lasso: 27


In [ ]:
print('Magnitude of Linear Regression coefficients:', abs(lr.coef_).sum())
print('Number of coeffients not equal to 0 for Linear Regression:', (lr.coef_!=0).sum())

Magnitude of Linear Regression coefficients: 346.3141575540715
Number of coeffients not equal to 0 for Linear Regression: 44


$ \ $

$(4)$ Based on those measures, which model is a "simpler" description of the relationship between the features and the target?

Aparentely is $las001$.


$ \ $

-----

## ***L1 vs. L2 Regularization***

As mentioned in the deck: Lasso and Ridge regression have the same syntax in SciKit Learn. Now we're going to compare the results from:


$$\text{Ridge vs. Lasso regression}$$

$ \ $

$(1)$ First of all, we import [`Ridge`.](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Ridge.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMML240ENSkillsNetwork34171862-2022-01-01)



In [ ]:
from sklearn.linear_model import Ridge

$ \ $

$(2)$  Define a Ridge object $r$ with  $alpha= 0.001$.


In [ ]:
r = Ridge(alpha = 0.001) 

$ \ $

$(3)$  Fit that object on $X$ and $y$.

In [ ]:
# entrenamos nuestro modelo s con la data X_train
# s = StandardScaler()
X_train_s = s.fit_transform(X_train)

# entrenamos nuestro modelo r con la data X_train_s, y_train
# r = Ridge(alpha = 0.001)
r.fit(X_train_s, y_train)

# obtenemos un conjunto de datos de prueba con el modelo s y la data X_test
X_test_s = s.transform(X_test)

# predecimos un conjunto de datos con el modelo r y la data X_test_s
y_pred_r = r.predict(X_test_s)

$ \ $ 

$(4)$ Print out the resulting coefficients.

In [ ]:
r.coef_

array([-21.188, -11.19 ,  17.846, -18.396,   0.341,  -7.285,  16.171,
         9.689,  -0.686,   0.084,   0.82 ,  -0.491,   0.375,  -2.035,
       -10.097, -32.536,   0.17 ,   0.025,   0.124,   0.09 ,  -2.956,
        -4.957, -16.113,   1.45 ,  -2.983,  -0.447,   0.736,   9.212,
        27.192,   1.591,   0.649,  -0.642,  -9.138, -27.418,   0.012,
         4.432,   0.827,   1.941,   0.523,  11.656,   4.4  ,   8.571,
        30.643,  15.914])

In [ ]:
las001.coef_

array([ 0.626, -0.   , -0.135, -0.   , -0.638, -1.308, -0.797, -0.787,
       -0.376,  0.326,  0.271, -0.132,  0.382, -0.577, -0.   , -0.167,
        0.211, -0.315,  0.326,  0.065, -1.319, -0.243,  0.   ,  0.206,
       -0.   , -0.465,  0.   , -0.   ,  0.   , -0.231,  0.665,  1.296,
       -0.   ,  0.   ,  0.021,  0.801,  0.   ,  0.   ,  1.111,  0.   ,
        0.   , -0.   ,  0.   ,  0.   ])

$ \ $ 

$(5)$ We take the sum of the absolute values of the coeficients.

In [ ]:
print("Ridge = ", np.sum(np.abs(r.coef_)))
print("Lasso [alpha = 0.001] = ", np.sum(np.abs(las001.coef_)))

Ridge =  334.04235981408164
Lasso [alpha = 0.001] =  13.797961138605485


$ \ $

$(6)$ We get the the number of non null elements from the model coefficients $r$ and $las001$.


In [ ]:
print("Non null elements from the model r =", np.sum(r.coef_ != 0))
print("Non null elements from the model las001 =", np.sum(las001.coef_ != 0))

Non null elements from the model r = 44
Non null elements from the model las001 = 27


$ \ $

$(7)$ We  obtain the $R^2$ score using the $r$ model and the $las001$ model.

In [ ]:
# predecimos un conjunto de datos con el modelo ridge r y la data X_pf_ss
y_pred = r.predict(X_pf_ss)

# calculamos R^2 teniendo en cuenta el conjunto de datos original y la data predecida y_pred
r2_score(y, y_pred)

0.6386693286319878

In [ ]:
# predecimos un conjunto de datos con el modelo lasso las001 y la data X_pf_ss
y_pred = las001.predict(X_pf_ss)

# calculamos R^2 teniendo en cuenta el conjunto de datos original y la data predecida y_pred
r2_score(y, y_pred)

0.6473206465455441

$ \ $

----

## ***Example: Does it matter when you scale?***


In [ ]:
# X_ss = s.fit_transform(X)
# y = california_data["MEDV"]
X_train, X_test, y_train, y_test = train_test_split(X_ss, y, test_size = 0.3, random_state = 72018)

In [ ]:
# creamos un modelo de regresión lineal
lr = LinearRegression()

# entrenamos nuestro modelo de regresion lineal usando la data X_train, y_train
lr.fit(X_train, y_train)

# predecimos un conjunto de valores con nuestro modelo de regresion lineal usando la data X_test
y_pred = lr.predict(X_test)

# calculamos R^2 teniendo en cuenta el conjunto de datos de prueba y la data predecida y_pred
r2_score(y_pred, y_test)

0.38783779372007054

In [ ]:
# X = california_data.drop("MEDV", axis=1)
# y = california_data["MEDV"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 72018)

In [ ]:
# creamos un modelo de escala estandar
s = StandardScaler()

# creamos un modelo de regresion lineal
lr_s = LinearRegression()

# entrenamos el modelo de escala estandar con la data X_train
X_train_s = s.fit_transform(X_train)

# entrenamos el modelo de regresion lineal con  la data X_train_s, y_train
lr_s.fit(X_train_s, y_train)

# creamos un conjunto de datos con el modelo de escala estandar y la data X_test
X_test_s = s.transform(X_test)

# predecimos un conjunto de datos con nuestro modelo de regresion lineal usando la data X_test_s
y_pred_s = lr_s.predict(X_test_s)

# calculamos R^2 teniendo en cuenta el conjunto de datos de prueba y la data predecida y_pred_s
r2_score(y_pred_s, y_test)

0.3878377937200701

**Conclusion:** It doesn't matter whether you scale before or afterwards, in terms of the raw predictions, for Linear Regression. However, it matters for other algorithms. Plus, as we'll see later, we can make scaling part of a `Pipeline`.
